Switch from running export to just running build

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -13,43 +13,43 @@ jobs:
       CI: true
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
     steps:
-    - uses: actions/checkout@v2
-    - name: Run Unit Tests
-      uses: actions/setup-node@v1
-      with:
-        node-version: 14.x
-    - run: |
-        echo "Run your tests here"
-    - if: env.AWS_ACCESS_KEY_ID == null
-      run: |
-        echo "AWS Credentials not found, This is expected for the first run as the repo is provisioned then secrets are injected at a later step."
-        exit 1
+      - uses: actions/checkout@v2
+      - name: Run Unit Tests
+        uses: actions/setup-node@v1
+        with:
+          node-version: 14.x
+      - run: |
+          echo "Run your tests here"
+      - if: env.AWS_ACCESS_KEY_ID == null
+        run: |
+          echo "AWS Credentials not found, This is expected for the first run as the repo is provisioned then secrets are injected at a later step."
+          exit 1
   build:
-      needs: unit-test
-      runs-on: ubuntu-latest
-      env:
-        CI: true
-      steps:
-        - uses: actions/checkout@v2
-        - name: Build Static Site
-          uses: actions/setup-node@v1
-          with:
-            node-version: 14.x
-        - name: Install Dependencies
-          run: npm install
-        - run: |
-            npm run export
-        - name: Upload build artifact to Github
-          uses: actions/upload-artifact@v1
-          with:
-            name: build-artifact
-            path: out/
+    needs: unit-test
+    runs-on: ubuntu-latest
+    env:
+      CI: true
+    steps:
+      - uses: actions/checkout@v2
+      - name: Build Static Site
+        uses: actions/setup-node@v1
+        with:
+          node-version: 14.x
+      - name: Install Dependencies
+        run: npm install
+      - run: |
+          npm run build
+      - name: Upload build artifact to Github
+        uses: actions/upload-artifact@v1
+        with:
+          name: build-artifact
+          path: out/
   deploy:
-      name: Deploy
-      runs-on: ubuntu-latest
-      needs: build
+    name: Deploy
+    runs-on: ubuntu-latest
+    needs: build
 
-      steps:
+    steps:
       # Once github action supports nested composite actions (anything `uses` is a composite action)
       # Therefore we cannot reuse the code as a separate composite action until it supports it,
       # current the deploy logic is in this file twice because of it
